[package]
name = "engine-data"
version = "0.1.0"
edition = "2021"

[dependencies]
engine-types = { path = "../types" }
polars = { version = "0.46", features = ["parquet", "lazy", "dtype-full", "temporal"] }
rayon = "1.10"
strum = { version = "0.26", features = ["derive"] }
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
